version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app:delegated
    tty: true
    stdin_open: true
    entrypoint: [ "sh", "-c", "/bin/bash"]
    working_dir: /app
    hostname: app
